version: "3.8"
services:
    backend:
        build: ./backend
        container_name: task_manager_backend_container
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/app
            - /app/node_modules
    frontend:
        build: ./frontend
        container_name: task_manager_frontend
        ports:
            - "3000:3000"
        stdin_open: true
